export type NotificationType =
  | 'BOOKING_CREATED'
  | 'BOOKING_CONFIRMED'
  | 'BOOKING_CANCELLED'
  | 'BOOKING_COMPLETED'
  | 'BOOKING_RESCHEDULE_REQUESTED'
  | 'BOOKING_RESCHEDULE_APPROVED'
  | 'BOOKING_RESCHEDULE_REJECTED'
  | 'PACKAGE_SUBMITTED'
  | 'PACKAGE_APPROVED'
  | 'PACKAGE_REJECTED'
  | 'PAYMENT_SUCCEEDED'
  | 'PAYMENT_REFUNDED'
  | 'TICKET_REPLY'
  | 'REVIEW_POSTED'
  | 'REVIEW_GUIDE_REPLY'
  | 'LICENCE_SUBMITTED'
  | 'LICENCE_VERIFIED'
  | 'LICENCE_REJECTED'
  | 'BOOKING_REJECTED'
  | 'VEHICLE_INSURANCE_DUE'
  | 'VEHICLE_MAINTENANCE_DUE'
  | 'TICKET_STATUS_CHANGED'
  | 'ACCOUNT_PROFILE_UPDATED'
  | 'ACCOUNT_PASSWORD_CHANGED'
  | 'ACCOUNT_DEACTIVATED'
  | 'ACCOUNT_REACTIVATED'
  | 'VEHICLE_APPROVED'
  | 'VEHICLE_REJECTED'
  | 'VEHICLE_STATUS_CHANGED'
  | 'VEHICLE_HIRE_REQUESTED'
  | 'VEHICLE_HIRE_CONFIRMED'
  | 'VEHICLE_HIRE_CANCELLED'
  | 'VEHICLE_HIRE_COMPLETED'
  | 'ROOM_RESERVATION_REQUESTED'
  | 'ROOM_RESERVATION_CONFIRMED'
  | 'ROOM_RESERVATION_CANCELLED'
  | 'ROOM_RESERVATION_COMPLETED'

// Matches com.tourlk.dto.NotificationResponseDto
export interface NotificationResponseDto {
  id: number
  type: NotificationType
  title: string
  message: string
  linkUrl: string | null
  read: boolean
  createdAt: string
}

// Matches com.tourlk.dto.UnreadCountResponseDto
export interface UnreadCountResponseDto {
  count: number
}
